"""change blogpost scheme

Revision ID: 137068116eee
Revises: 3322fcd3d5d8
Create Date: 2026-04-11 13:11:47.864042

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '137068116eee'
down_revision = '3322fcd3d5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
