"""add_phone_to_contacts

Revision ID: 827700c305bd
Revises: e68154b474da
Create Date: 2025-12-27 16:46:19.627106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '827700c305bd'
down_revision = 'e68154b474da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'phone')
    # ### end Alembic commands ###
