"""create blog_posts table

Revision ID: 8b78faf47d11
Revises: 8bb9b562961f
Create Date: 2026-01-04 13:20:57.664670

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b78faf47d11'
down_revision = '8bb9b562961f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create blog_posts table if it doesn't exist
    op.execute("""
        CREATE TABLE IF NOT EXISTS blog_posts (
            id SERIAL PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            content VARCHAR(10000) NOT NULL,
            slug VARCHAR(255) NOT NULL UNIQUE,
            description TEXT,
            keywords TEXT,
            image TEXT,
            reading_time_minutes INTEGER,
            created_at TIMESTAMP,
            updated_at TIMESTAMP
        )
    """)
    # Drop test_table if it exists
    op.execute("DROP TABLE IF EXISTS test_table")
    op.alter_column('contacts', 'message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # Create foreign key with explicit name only if it doesn't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'tour_date_tour_id_fkey'
            ) THEN
                ALTER TABLE tour_date 
                ADD CONSTRAINT tour_date_tour_id_fkey 
                FOREIGN KEY (tour_id) REFERENCES tours(id);
            END IF;
        END $$;
    """)
    op.alter_column('users', 'image',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # Drop foreign key with explicit name
    op.drop_constraint('tour_date_tour_id_fkey', 'tour_date', type_='foreignkey')
    op.alter_column('contacts', 'message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_table_pkey'))
    )
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
